-- 1) Profiles table (extends auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  role text not null default 'player' check (role in ('player', 'admin', 'super_admin')),
  created_at timestamptz not null default now()
);

-- 2) Gameplay content
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  word text not null,
  hint text not null
);

create table if not exists public.scoreboard (
  id bigint generated by default as identity primary key,
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  wins integer not null default 0 check (wins >= 0)
);

-- 3) Trigger: auto-create profile on signup
create or replace function public.create_profile_after_signup()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)), 'player')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup
after insert on auth.users
for each row execute function public.create_profile_after_signup();

-- 4) Enable Row Level Security
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.words enable row level security;
alter table public.scoreboard enable row level security;

-- 5) Helper role functions
create or replace function public.current_user_role()
returns text
language sql
stable
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin_or_super_admin()
returns boolean
language sql
stable
as $$
  select public.current_user_role() in ('admin', 'super_admin');
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
as $$
  select public.current_user_role() = 'super_admin';
$$;

-- 6) Profiles policies
drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin_or_super_admin());

drop policy if exists "super admin can manage profiles" on public.profiles;
create policy "super admin can manage profiles"
on public.profiles for all
to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

-- 7) Categories and words policies
drop policy if exists "authenticated read categories" on public.categories;
create policy "authenticated read categories"
on public.categories for select
to authenticated
using (true);

drop policy if exists "admin manage categories" on public.categories;
create policy "admin manage categories"
on public.categories for all
to authenticated
using (public.is_admin_or_super_admin())
with check (public.is_admin_or_super_admin());

drop policy if exists "authenticated read words" on public.words;
create policy "authenticated read words"
on public.words for select
to authenticated
using (true);

drop policy if exists "admin manage words" on public.words;
create policy "admin manage words"
on public.words for all
to authenticated
using (public.is_admin_or_super_admin())
with check (public.is_admin_or_super_admin());

-- 8) Scoreboard policies
drop policy if exists "authenticated read scoreboard" on public.scoreboard;
create policy "authenticated read scoreboard"
on public.scoreboard for select
to authenticated
using (true);

drop policy if exists "players update own score row" on public.scoreboard;
create policy "players update own score row"
on public.scoreboard for update
to authenticated
using (profile_id = auth.uid() or public.is_admin_or_super_admin())
with check (profile_id = auth.uid() or public.is_admin_or_super_admin());

drop policy if exists "players insert own score row" on public.scoreboard;
create policy "players insert own score row"
on public.scoreboard for insert
to authenticated
with check (profile_id = auth.uid() or public.is_admin_or_super_admin());

drop policy if exists "admin reset any score row" on public.scoreboard;
create policy "admin reset any score row"
on public.scoreboard for delete
to authenticated
using (public.is_admin_or_super_admin());

-- 9) Manual first super admin seed example:
-- update public.profiles
-- set role = 'super_admin'
-- where id = 'PUT_FIRST_USER_UUID_HERE';
